**Python Class**

In [23]:
class Dog:
    species = "puddle"  # Class attribute

    def __init__(self, name, age):
        self.name = name  # Instance attribute
        self.age = age  # Instance attribute


In [24]:
# Creating an object of the Dog class
dog1 = Dog("Felfel", 3)

print(dog1.name)
print(dog1.species)

Felfel
puddle


In [25]:
class Dog:

    def __init__(self, name, age):
        self.name = name
        self.age = age

    def get_age_in_human_years(self, coefficient):
      return coefficient * self.age


In [26]:
dog2 = Dog("Namak", 2)

print(dog2.name)
print(dog2.get_age_in_human_years(7))

Namak
14


**Python Encapsulation**

*   Public Members: Accessible from anywhere.
*   Protected Members: Accessible within the class and its subclasses.
*   Private Members: Accessible only within the class.


In [ ]:
class Dog:
    def __init__(self, name, breed, age):
        self.name = name  # Public attribute
        self._breed = breed  # Protected attribute
        self.__age = age  # Private attribute

    # Public method
    def get_info(self):
        return f"Name: {self.name}, Breed: {self._breed}, Age: {self.__age}"

    # Getter and Setter for private attribute
    def get_age(self):
        return self.__age

    def set_age(self, age):
        if age > 0:
            self.__age = age
        else:
            print("Invalid age!")

In [ ]:
dog = Dog("Felfel", "Labrador", 3)

# Accessing public member
print(dog.name)  # Accessible

# Accessing protected member
print(dog._breed)  # Accessible but discouraged outside the class

# Accessing private member using getter
print(dog.get_age())

# Modifying private member using setter
dog.set_age(5)
print(dog.get_info())

Felfel
Labrador
3
Name: Felfel, Breed: Labrador, Age: 5


# **Data Processing**

**NumPy**

In [3]:
import numpy as np

# Creating a 1D array
x = np.array([1, 2, 3])

# Creating a 2D array
y = np.array([[1, 2], [3, 4]])

# Creating a 3D array
z = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

print(x)
print("############")
print(y)
print("############")
print(z)


[1 2 3]
############
[[1 2]
 [3 4]]
############
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


## Checking Array Properties

In [27]:
arr = np.array([1, 2, 3, 4, 5])
print('Shape:', arr.shape)
print('Size:', arr.size)
print('Data Type:', arr.dtype)

Shape: (5,)
Size: 5
Data Type: int64


##Numpy Functions

In [4]:

a1_zeros = np.zeros((3, 3))
a2_ones = np.ones((2, 2))
a3_range = np.arange(0, 10, 2)

print(a1_zeros)
print(a2_ones)
print(a3_range)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]]
[0 2 4 6 8]


NumPy Array Indexing

In [5]:
# Create a 1D array
arr1d = np.array([10, 20, 30, 40, 50])

# Single element access
print("Single element access:", arr1d[2])

# Negative indexing
print("Negative indexing:", arr1d[-1])

# Create a 2D array
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Multidimensional array access
print("Multidimensional array access:", arr2d[1, 0])


Single element access: 30
Negative indexing: 50
Multidimensional array access: 4


Slicing

In [6]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])
#elements from index 1 to 3
print("Range of Elements:",arr[1:4])

#all rows, second column
print("Multidimensional Slicing:", arr[:, 1])


Range of Elements: [[4 5 6]]
Multidimensional Slicing: [2 5]


Advanced Indexing

In [28]:
import numpy as np
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, -100])

# Integer array indexing
indices = np.array([1, 3, 5])
print ("Integer array indexing:", arr[indices])

# boolean array indexing
cond = arr > 0
print ("\nElements greater than 0:\n", arr[cond])


Integer array indexing: [20 40 60]

Elements greater than 0:
 [10 20 30 40 50 60 70 80 90]


## Reshaping Arrays

In [29]:
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
reshaped = arr2d.reshape(3, 2)
print(reshaped)

[[1 2]
 [3 4]
 [5 6]]


**Basic Operations**

Element-wise Operations

In [30]:
import numpy as np

x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

# Addition
add = x + y
print("Addition:",add)

# Subtraction
subtract = x - y
print("substration:",subtract)

# Multiplication
multiply = x * y
print("multiplication:",multiply)

# Division
divide = x / y
print("division:", divide)


Addition: [5 7 9]
substration: [-3 -3 -3]
multiplication: [ 4 10 18]
division: [0.25 0.4  0.5 ]


## Broadcasting in NumPy

In [31]:
arr = np.array([1, 2, 3])
print(arr + 10)  # Adds 10 to each element

[11 12 13]


Unary Operation

In [32]:
import numpy as np

# Example array with both positive and negative values
arr = np.array([-3, -1, 0, 1, 3])

# Applying a unary operation: absolute value
result = np.absolute(arr)
print("Absolute value:", result)


Absolute value: [3 1 0 1 3]


**NumPy ufuncs**

In [17]:
import numpy as np

# create an array of sine values
a = np.array([0, np.pi/2, np.pi])
print ("Sine values of array elements:", np.sin(a))

# exponential values
a = np.array([0, 1, 2, 3])
print ("Exponent of array elements:", np.exp(a))

# square root of array values
print ("Square root of array elements:", np.sqrt(a))


Sine values of array elements: [0.0000000e+00 1.0000000e+00 1.2246468e-16]
Exponent of array elements: [ 1.          2.71828183  7.3890561  20.08553692]
Square root of array elements: [0.         1.         1.41421356 1.73205081]


**NumPy Sorting Arrays**

In [22]:
import numpy as np

# set alias names for dtypes
dtypes = [('name', 'S10'), ('grad_year', int), ('cgpa', float)]

# Values to be put in array
values = [('Hrithik', 2009, 8.5), ('Ajay', 2008, 8.7),
           ('Pankaj', 2008, 7.9), ('Aakash', 2009, 9.0)]

# Creating array
arr = np.array(values, dtype = dtypes)
print ("\nArray sorted by names:\n",
            np.sort(arr, order = 'name'))

print ("Array sorted by graduation year and then cgpa:\n",
                np.sort(arr, order = ['grad_year', 'cgpa']))



Array sorted by names:
 [(b'Aakash', 2009, 9. ) (b'Ajay', 2008, 8.7) (b'Hrithik', 2009, 8.5)
 (b'Pankaj', 2008, 7.9)]
Array sorted by graduation year and then cgpa:
 [(b'Pankaj', 2008, 7.9) (b'Ajay', 2008, 8.7) (b'Hrithik', 2009, 8.5)
 (b'Aakash', 2009, 9. )]
